app = 'tomontheinternet'
primary_region = 'yyz'
kill_signal = 'SIGTERM'

[build]

[env]
DATABASE_PATH = '/mnt/name/name.db'
PHX_HOST = 'tomontheinternet.com'
PORT = '8080'

[[mounts]]
source = 'name'
destination = '/mnt/name'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
